using FluentMigrator;
using Template.Persistence.Common;

namespace Template.Persistence.Migrations
{
    [Migration(1, "Identity tables")]
    public class IdentityTables : SqlMigration
    {
        protected override string GetUpSql(IServiceProvider services) =>
@"create table users
(
    id bigint not null generated by default as identity
        constraint pk_identity_users
        primary key,
    phone_number            varchar(256),
    email                   varchar(256),
    password_hash           text,
    password_salt           text,
    role                    bigint,
    created_at              timestamp with time zone,
    updated_at              timestamp with time zone,
    deleted_at              timestamp with time zone,
    is_deleted              boolean

);



create table user_profiles
(
    id bigint not null generated by default as identity
        constraint pk_user_profiles
        primary key,

    user_id                 bigint not null 
                            constraint fk_user_profiles_user_id__identity_users_id
	                            references identity_users
	                            on delete cascade,

    first_name              varchar(256),
    second_name             varchar(256),
    patronymic              varchar(256), 
    created_at              timestamp with time zone,
    updated_at              timestamp with time zone,
    deleted_at              timestamp with time zone,
    is_deleted              boolean

);

";


        protected override string GetDownSql(IServiceProvider services)
        {
            throw new NotImplementedException();
        }
    }
}
